services:
  # Django app
  blog_with_authentication_backend:
    container_name: django_blog_with_authentication
    build: .
    command: uvicorn core.asgi:application --host 0.0.0.0 --port 8003 --reload
    volumes:
      - .:/app
    ports: 
      - 8003:8003
    depends_on:
      - blog_with_authentication_django_redis
      - blog_with_authentication_django_db

  # Redis
  blog_with_authentication_django_redis:
    image: redis
    container_name: blog_with_authentication_django_redis
    ports:
      - 6380:6381

  # Database
  blog_with_authentication_django_db:
    image: postgres
    container_name: postgresql_blog_with_authentication
    restart: always
    environment: 
      POSTGRES_DB: django_db
      POSTGRES_USER: django
      POSTGRES_PASSWORD: postgres
    ports:
      - 5436:5434
    volumes:
      - .dbdata:/var/lib/postgresql

  # Celery
  celery_worker:
    container_name: blog_celery_worker
    build: .
    command: celery -A core worker --loglevel=info
    volumes:
      - .:/app
    ports:
      - 8004:8004
    depends_on:
      - blog_with_authentication_django_redis
      - blog_with_authentication_django_db

  # Celery beat
  celery_beat:
    container_name: blog_celery_beat
    build: .
    command: celery -A core beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    ports:
      - 8005:8005
    depends_on:
      - blog_with_authentication_django_redis
      - blog_with_authentication_django_db
